name: Deploy

on:
  push:
    branches:
      - main
env:
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Deploy to Heroku
        env:
          HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
          HEROKU_APP_NAME: prod
        if: github.ref == 'refs/heads/main' && job.status == 'success'
        run: |
          git push https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git origin/main:main

      - name: Slack Notification on Success
        uses: rtCamp/action-slack-notify@master
        if: success()
        env:
          SLACK_CHANNEL: sample-ci
          SLACK_TITLE: Deploy Success [prod]
          SLACK_COLOR: good

      - name: Slack Notification on Failure
        uses: rtCamp/action-slack-notify@master
        if: failure()
        env:
          SLACK_CHANNEL: sample-ci
          SLACK_TITLE: Deploy Failure [prod]
          SLACK_COLOR: danger
