name: Run PHPUnit

on:
  push:
    branches:
      - feature/*
      - fix/*
      - refactor/*
  pull_request:
    branches:
      - feature/*

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testing
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    env:
       DB_CONNECTION: mysql
       DB_HOST: 127.0.0.1
       DB_PORT: 3306
       DB_DATABASE: testing
       DB_USERNAME: root
       DB_PASSWORD: root
       APP_ENV: testing
       APP_URL: http://localhost
       APP_HOST: localhost.local

    defaults:
       run:
         working-directory: .
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          tools: composer:v2

      - name: Cache vendor
        id: cache
        uses: actions/cache@v1
        with:
          path: ./vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: composer install
        if: steps.cache.outputs.cache-hit != 'true'
        run: composer install -n --prefer-dist

      - name: composer dump autoload
        run: composer dump-autoload

      - name: generate key
        run: php artisan key:generate --env=testing

      - name: migrate
        run: php artisan migrate

      - name: Execute tests (Unit tests) via PHPUnit
        run: |
          php artisan config:clear
          ./vendor/bin/phpunit --coverage-text --colors=never --testsuite Unit > storage/logs/coverage.log
          cat storage/logs/coverage.log

      - name: Cat Test Result
        run: |
          cat storage/logs/coverage.log
        if: ${{ failure() }}

      - name: Sed Coverage Report
        run: |
          sed -E "s/"$'\E'"\[([0-9]{1,2}(;[0-9]{1,2})*)?m//g" | \
          grep "Code Coverage Report:" -A6 storage/logs/coverage.log | sed -e "s/^ *//" | sed -e "s/ *$//" | sed -e "/^ *$/d" > storage/logs/coverage-summary.log

      - name: Read coverage summary
        id: coverage-summary
        uses: juliangruber/read-file-action@v1
        with:
          path: ./storage/logs/coverage-summary.log

      - name: Get id
        uses: jwalton/gh-find-current-pr@v1
        id: finder

      - name: Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          number: ${{ steps.finder.outputs.pr }}
          header: header-of-comment
          message: |
            ${{ steps.coverage-summary.outputs.content }}
